"""add_id_and_created_at_to_centros_treinamento

Revision ID: 0270930e5616
Revises: be93ec6ba7c8
Create Date: 2025-08-09 16:36:47.606303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0270930e5616'
down_revision: Union[str, Sequence[str], None] = 'be93ec6ba7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centros_treinamento', 'created_at')
    # ### end Alembic commands ###
